/**
 * Pure cryptographic building blocks — no database, no HTTP — so they
 * can be tested in isolation. server.js and store.js are the only
 * callers.
 *
 * Two different hashing choices are used here deliberately, for two
 * different kinds of secret:
 *
 * - Passwords are hashed with scrypt, a slow, memory-hard KDF. A
 *   password is low-entropy (people reuse short, guessable ones), so
 *   the hash needs to be expensive to brute-force.
 * - Session tokens are hashed with plain SHA-256. A token is 32
 *   random bytes generated by us — already far too high-entropy to
 *   brute-force — so a slow KDF here would only waste CPU on every
 *   single authenticated request for no security benefit. SHA-256
 *   just needs to make a stolen database not directly usable as
 *   login tokens.
 */

const crypto = require('crypto');

const SCRYPT_KEYLEN = 64;

function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(password, salt, SCRYPT_KEYLEN).toString('hex');
  return { hash, salt };
}

function verifyPassword(password, hash, salt) {
  const candidate = crypto.scryptSync(password, salt, SCRYPT_KEYLEN);
  const stored = Buffer.from(hash, 'hex');
  if (candidate.length !== stored.length) return false;
  return crypto.timingSafeEqual(candidate, stored);
}

function generateToken() {
  return crypto.randomBytes(32).toString('hex');
}

function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex');
}

const SESSION_LIFETIME_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

module.exports = { hashPassword, verifyPassword, generateToken, hashToken, SESSION_LIFETIME_MS };
